name: Go

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - uses: actions/checkout@v2
      - name: Run tests
        run: go test -v ./...
        env:
          PG_CONN: postgresql://postgres:postgres@127.0.0.1:5432/postgres?sslmode=disable

  semantic-release:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run semantic-release
        if:
          github.repository == 'global-soft-ba/casbin-pgx-adapter' && (github.event_name
          == 'push' || (github.event_name == 'pull_request' &&
          github.event.action == 'closed' && github.event.pull_request.merged ==
          true))
        run: |
          npm install --save-dev semantic-release@17.2.4
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
