name: Go

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - uses: actions/checkout@v2
      - name: Run tests
        run: go test -v ./...
        env:
          PG_CONN: postgresql://postgres:postgres@127.0.0.1:5432/postgres?sslmode=disable
